name: Build

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  build:
    uses: Jikoo/PlanarActions/.github/workflows/ci_gradle.yml@master
    with:
      include-artifacts: "./enchanting-bundler/build/libs/*.jar"
